// This module is only used to generate documentation. Do NOT import it anywhere else!
/**
 * This namespace contains hook events that are called by Quench.
 * Each hook contains a remark pointing out with which function it is called.
 *
 * @see [Foundry VTT Hooks class](https://foundryvtt.com/api/classes/client.Hooks.html)
 * @module hookEvents
 */

/**
 * A hook event that fires when Quench is ready to register batches.
 *
 * @group Initialization
 * @see {@link quench!Quench#registerBatch quench.registerBatch}
 * @remarks This is called by {@link Hooks.callAll}
 * @param quench - The global {@link quench!Quench} instance
 */
export declare const quenchReady: Hooks.StaticCallbacks["quenchReady"];

/**
 * A hook event that fires when a batch run is completed and Quench's reports are ready.
 *
 * @group Reports
 * @remarks This is called by {@link Hooks.callAll}
 * @param reports - An object containing reports generated by the batch run
 */
export declare const quenchReports: Hooks.StaticCallbacks["quenchReports"];
